apprango/urls.py
__author__ = 'gray'

from django.conf.urls import patterns, url
from apprango import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^category/(?P<slug_item>[\w\-]+)/$', views.category, name='category'),
                       url(r'^add-category/$', views.add_category, name='add-category'),
                       url(r'^(?P<slug_item>[\w\-]+)/add-page/$', views.add_page, name='add-page'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.login, name='login'),
                       url(r'^restricted/$', views.restricted, name='restricted'),
                       url(r'^logout/$', views.logout, name='logout'))

rango_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


# a class to override the default behaviour upon a succesful login
class ModifiedRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rango_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('apprango.urls', namespace="apprango")),
    url(r'^accounts/register/$', ModifiedRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, namspace='media')

apprango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile-images', blank=True)

    def __unicode__(self):
        return self.user.username

apprango/forms.py
__author__ = 'gray'

from django import forms
from apprango.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CatForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter a name for this Category")
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ("name", )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter a title for this Page")
    url = forms.URLField(max_length=256, help_text="Enter Page URL")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ("category", )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', )

apprango/views.py
from django.shortcuts import render
from apprango.models import Category, Page
from apprango.forms import CatForm, PageForm, UserForm, UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse, resolve
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import logout as dlogout
from django.contrib.auth import login as dlogin
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    # get and return the first 5 items in the Categories table
    all_categories = Category.objects.order_by("likes")[:5]
    return render(request, "apprango/index.html", {"objects": all_categories})


def category(request, slug_item):
    # a context item to be sent to the view
    context_item = {}

    try:
        # get the category with a matching slug
        category_ = Category.objects.get(slug=slug_item)
        context_item['name'] = category_.name

        # get all pages with a matching category
        pages = Page.objects.filter(category=category_)
        context_item['pages'] = pages

        context_item['category'] = category_

    except Category.DoesNotExist:
        # the requested category was not found
        # do nothing and go back
        # all necessary error messages are in the view
        pass

    return render(request, 'apprango/category.html', context_item)


@login_required
def add_category(request):
    if request.method == "POST":
        posted_form = CatForm(request.POST)

        if posted_form.is_valid():
            posted_form.save(commit=True)

            return HttpResponseRedirect(reverse("apprango:index"))
        else:
            messages.error(request, 'The category could not be created because of errors on the form.')
            return HttpResponseRedirect(reverse("apprango:add-category"))

    else:
        new_form = CatForm()
        return render(request, "apprango/add-category.html", {"form": new_form})


@login_required
def add_page(request, slug_item):
    try:
        catg = Category.objects.get(slug=slug_item)
    except Category.DoesNotExist:
        catg = None

    if request.method == 'POST':
        frm = PageForm(request.POST)

        if frm.is_valid():
            if catg:
                page = frm.save(commit=False)
                page.category = catg
                page.save()

                return HttpResponseRedirect(reverse('apprango:index'))
        else:
            # messages.error(request, 'The page could not be added because of errors on the form.')
            # return HttpResponseRedirect(reverse('apprango:add-page', args=(catg.slug, ), kwargs={'form': frm}))
            context_dict = {'form': frm, 'category': catg}
            return render(request, 'apprango/add-page.html', context_dict)
    else:
        frm = PageForm()
        context_dict = {'form': frm, 'category': catg}
        return render(request, 'apprango/add-page.html', context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        form_user = UserForm(data=request.POST)
        form_profile = UserProfileForm(data=request.POST)

        if form_profile.is_valid() and form_user.is_valid():
            usr = form_user.save(commit=False)
            usr.set_password(usr.password)
            usr.save()

            prfl = form_profile.save(commit=False)
            prfl.user = usr

            if 'picture' in request.FILES:
                prfl.picture = request.FILES['picture']

            prfl.save()
            registered = True
            context_dict = {'frm_user': form_user, 'frm_profile': form_profile, 'registered': registered}
            return render(request, 'apprango/register.html', context_dict)

        else:
            context_dict = {'frm_user': form_user, 'frm_profile': form_profile}
            return render(request, 'apprango/register.html', context_dict)

    else:
        form_user = UserForm()
        form_profile = UserProfileForm()
        context_dict = {'frm_user': form_user, 'frm_profile': form_profile, 'registered': registered}
        return render(request, 'apprango/register.html', context_dict)


def login(request):
    if request.method == 'POST':
        uname = request.POST['uname']
        passw = request.POST['passw']

        usr = authenticate(username=uname, password=passw)

        if usr and usr.is_active:
            dlogin(request, usr)
            next_pg = request.POST['next']

            if next_pg:
                pg_match = resolve(next_pg)
                return HttpResponseRedirect(reverse(pg_match.view_name, kwargs=pg_match.kwargs))
            else:
                return HttpResponseRedirect(reverse('apprango:index'))
        else:
            messages.error(request, 'Your login credentials are invalid')
            return HttpResponseRedirect(reverse('apprango;login.html'))

    else:
        next_pg = request.GET.get('next', False)
        if next_pg:
            return render(request, 'apprango/login.html', {'next': next_pg})
        else:
            return render(request, 'apprango/login.html')


@login_required
def restricted(request):
    return HttpResponse('Hello. It appears you are logged in :)')


@login_required
def logout(request):
    dlogout(request)
    return HttpResponseRedirect(reverse('apprango:index'))

apprango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    {% load rango-extras %}

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/rango/">AppRango</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'apprango:index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'apprango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'apprango:add-category' %}">Add a New Category</a></li>
                    <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
{#                <li><a href="{% url 'about' %}">About</a></li>#}

            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block sideblock %}
                {% get_cat_list category %}
            {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <div>
                {% block bodyblock %}{% endblock %}
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>