apprango/urls.py
__author__ = 'gray'

from django.conf.urls import patterns, url
from apprango import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^category/(?P<slug_item>[\w\-]+)/$', views.category, name='category'),
                       url(r'^add-category/$', views.add_category, name='add-category'),
                       url(r'^(?P<slug_item>[\w\-]+)/add-page/$', views.add_page, name='add-page'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.login, name='login'),
                       url(r'^restricted/$', views.restricted, name='restricted'),
                       url(r'^logout/$', views.logout, name='logout'))

rango_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


# a class to override the default behaviour upon a succesful login
class ModifiedRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rango_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('apprango.urls', namespace="apprango")),
    url(r'^accounts/register/$', ModifiedRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, namspace='media')

apprango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile-images', blank=True)

    def __unicode__(self):
        return self.user.username

apprango/forms.py
__author__ = 'gray'

from django import forms
from apprango.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CatForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter a name for this Category")
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ("name", )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter a title for this Page")
    url = forms.URLField(max_length=256, help_text="Enter Page URL")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ("category", )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', )

apprango/views.py
from django.shortcuts import render
from apprango.models import Category, Page
from apprango.forms import CatForm, PageForm, UserForm, UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse, resolve
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import logout as dlogout
from django.contrib.auth import login as dlogin
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    # get and return the first 5 items in the Categories table
    all_categories = Category.objects.order_by("likes")[:5]
    return render(request, "apprango/index.html", {"objects": all_categories})


def category(request, slug_item):
    # a context item to be sent to the view
    context_item = {}

    try:
        # get the category with a matching slug
        category_ = Category.objects.get(slug=slug_item)
        context_item['name'] = category_.name

        # get all pages with a matching category
        pages = Page.objects.filter(category=category_)
        context_item['pages'] = pages

        context_item['category'] = category_

    except Category.DoesNotExist:
        # the requested category was not found
        # do nothing and go back
        # all necessary error messages are in the view
        pass

    return render(request, 'apprango/category.html', context_item)


@login_required
def add_category(request):
    if request.method == "POST":
        posted_form = CatForm(request.POST)

        if posted_form.is_valid():
            posted_form.save(commit=True)

            return HttpResponseRedirect(reverse("apprango:index"))
        else:
            messages.error(request, 'The category could not be created because of errors on the form.')
            return HttpResponseRedirect(reverse("apprango:add-category"))

    else:
        new_form = CatForm()
        return render(request, "apprango/add-category.html", {"form": new_form})


@login_required
def add_page(request, slug_item):
    try:
        catg = Category.objects.get(slug=slug_item)
    except Category.DoesNotExist:
        catg = None

    if request.method == 'POST':
        frm = PageForm(request.POST)

        if frm.is_valid():
            if catg:
                page = frm.save(commit=False)
                page.category = catg
                page.save()

                return HttpResponseRedirect(reverse('apprango:index'))
        else:
            # messages.error(request, 'The page could not be added because of errors on the form.')
            # return HttpResponseRedirect(reverse('apprango:add-page', args=(catg.slug, ), kwargs={'form': frm}))
            context_dict = {'form': frm, 'category': catg}
            return render(request, 'apprango/add-page.html', context_dict)
    else:
        frm = PageForm()
        context_dict = {'form': frm, 'category': catg}
        return render(request, 'apprango/add-page.html', context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        form_user = UserForm(data=request.POST)
        form_profile = UserProfileForm(data=request.POST)

        if form_profile.is_valid() and form_user.is_valid():
            usr = form_user.save(commit=False)
            usr.set_password(usr.password)
            usr.save()

            prfl = form_profile.save(commit=False)
            prfl.user = usr

            if 'picture' in request.FILES:
                prfl.picture = request.FILES['picture']

            prfl.save()
            registered = True
            context_dict = {'frm_user': form_user, 'frm_profile': form_profile, 'registered': registered}
            return render(request, 'apprango/register.html', context_dict)

        else:
            context_dict = {'frm_user': form_user, 'frm_profile': form_profile}
            return render(request, 'apprango/register.html', context_dict)

    else:
        form_user = UserForm()
        form_profile = UserProfileForm()
        context_dict = {'frm_user': form_user, 'frm_profile': form_profile, 'registered': registered}
        return render(request, 'apprango/register.html', context_dict)


def login(request):
    if request.method == 'POST':
        uname = request.POST['uname']
        passw = request.POST['passw']

        usr = authenticate(username=uname, password=passw)

        if usr and usr.is_active:
            dlogin(request, usr)
            next_pg = request.POST['next']

            if next_pg:
                pg_match = resolve(next_pg)
                return HttpResponseRedirect(reverse(pg_match.view_name, kwargs=pg_match.kwargs))
            else:
                return HttpResponseRedirect(reverse('apprango:index'))
        else:
            messages.error(request, 'Your login credentials are invalid')
            return HttpResponseRedirect(reverse('apprango;login.html'))

    else:
        next_pg = request.GET.get('next', False)
        if next_pg:
            return render(request, 'apprango/login.html', {'next': next_pg})
        else:
            return render(request, 'apprango/login.html')


@login_required
def restricted(request):
    return HttpResponse('Hello. It appears you are logged in :)')


@login_required
def logout(request):
    dlogout(request)
    return HttpResponseRedirect(reverse('apprango:index'))

apprango/templates/apprango/add-category.html
{% extends 'base.html' %}

{% block bodyblock %}

    <h1>Add Category</h1>
    <p>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </p>

    <form id="cat_form" action="{% url 'apprango:add-category' %}" method="post">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}

        <input type="submit" name="submit" value="Create"/>
    </form>

{% endblock %}

apprango/templates/apprango/add-page.html
{% extends 'base.html' %}

{% block bodyblock %}

    <h1>Add Page</h1>
    <p>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </p>
    {% if category == None %}
        <p>Category does not exist.</p>
    {% else %}
        <form id="cat_form" action="{% url 'apprango:add-page' category.slug %}" method="post">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <p>{{ field.errors }}</p>
            <p>{{ field.help_text }}
                {{ field }}</p>
        {% endfor %}
        <input type="submit" name="submit" value="Create"/>
    {% endif %}
</form>

{% endblock %}

apprango/templates/apprango/categories.html
{% if categs %}
    <ul class="nav nav-sidebar">
        {% for categ in categs %}
            {% if categ == active_cat %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
                <a href="{% url 'apprango:category' categ.slug %}"> {{ categ.name }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <strong>There are no categories present.</strong>
{% endif %}

apprango/templates/apprango/category.html
{% extends 'base.html' %}

{% block bodyblock %}

    <body>
    <h1>{{ name }}</h1>

    {% if category %}
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>This category has no pages yet.</strong>
        {% endif %}

        <p>Add a new <a href="{% url 'apprango:add-page' category.slug %}">page</a></p>
    {% else %}
        <strong>The category {{ name }} does not exist.</strong>
    {% endif %}

{% endblock %}

apprango/templates/apprango/index.html
{% extends 'base.html'%}

{% block bodyblock %}

<p>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
</p>
{% if user.is_authenticated %}
    <p>Hello {{ user.username }}. You are... authenticated!</p>
{% endif %}

<p>Below is a listing of all Categories in the system.</p>
{% if objects %}
    <ul>
        {% for category in objects %}
            <li><a href="{% url 'apprango:category' category.slug %}"> {{ category.name }} </a></li>
        {% endfor %}
    </ul>
    <p>You can add a new <a href="{% url 'apprango:add-category' %}">category</a></p>
{% else %}
    <strong>There are no categories entered yet.</strong>
{% endif %}

{% endblock %}

apprango/templates/apprango/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Apprango Login</title>
</head>
<body>
    <h1>Login Here</h1>
    <form id="login_frm" method="post" action="{% url 'apprango:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        Username: <input type="text" name="uname" id="uname" />
        <br />
        Password: <input type="password" name="passw" id="passw" />
        <br />
        <input type="submit" name="submit" value="Login" />
    </form>
</body>
</html>

apprango/templates/apprango/register.html
{% extends 'base.html'%}

{% block bodyblock %}

<body>
    <h1>Register with Apprango</h1>

    {% if registered %}
        Registration was a success. Proceed to the Login Page
    {% else %}
        Please register as a user...

        <form id="reg_form" method="post" action="{% url 'apprango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ frm_user.as_p }}
            {{ frm_profile.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}

{% endblock %}